package edu.guilford;

import java.util.Scanner;

public class User {

    // Scanner object
    Scanner scan = new Scanner(System.in);


    // User's attributes 
    private String firstName;
    private String lastName;
    private String email;
    private String favoriteColor;
    private int favoriteNumber;
    private String favoriteAnimal;

    // Password attribute
    private String thePassword;

    // constructors
    public User() {
        firstName = "";
        lastName = "";
        email = "";
        favoriteColor = "";
        favoriteNumber = 0;
        favoriteAnimal = "";


    }

    public User(String firstName, String lastName, String email, String favoriteColor, int favoriteNumber, String favoriteAnimal) { 
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.favoriteColor = favoriteColor;
        this.favoriteNumber = favoriteNumber;
        this.favoriteAnimal = favoriteAnimal;
    }

    // getters and setters
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFavoriteColor() {
        return favoriteColor;
    }

    public void setFavoriteColor(String favoriteColor) {
        this.favoriteColor = favoriteColor;
    }

    public int getFavoriteNumber() {
        return favoriteNumber;
    }

    public void setFavoriteNumber(int favoriteNumber) {
        this.favoriteNumber = favoriteNumber;
    }

    public String getFavoriteAnimal() {
        return favoriteAnimal;
    }

    public void setFavoriteAnimal(String favoriteAnimal) {
        this.favoriteAnimal = favoriteAnimal;
    }

    public String getThePassword() {
        return thePassword;
    }

    public void setThePassword(String thePassword) {
        this.thePassword = thePassword;
    }


    // Write a method that generates a password based on the user's favorite first name, last name, favorite color, favorite number, and favorite animal.

    public void generatePassword() {
        // The password is generated by concatenating the first letter of the user's 
        // first name, last name, favorite color, favorite number, and favorite animal.
        String userPassword = "";
        userPassword += firstName.substring(0, 1);
        userPassword += lastName.substring(0, 1);
        userPassword += favoriteColor.substring(0, 1);
        userPassword += favoriteNumber;
        userPassword += favoriteAnimal.substring(0, 1);

        setThePassword(userPassword);
    }

    // Obtain all of the user's information by using the Scanner class

    // This method obtains the information from User 1 and prints it out 
    public void obtainUser1Info() {
        // The Scanner class is used to obtain the user 1's information

        System.out.println("User 1, please enter your first name: ");
        setFirstName(scan.nextLine());

        System.out.println("\n" + "Please enter your last name: ");
        setLastName(scan.nextLine());

        System.out.println("\n" + "Please enter your email: ");
        setEmail(scan.nextLine());

        System.out.println("\n" + "Please enter your favorite color: ");
        setFavoriteColor(scan.nextLine());

        System.out.println("\n" + "Please enter your favorite animal: ");
        setFavoriteAnimal(scan.nextLine());

        System.out.println("\n" + "Please enter your favorite number: ");
        setFavoriteNumber(scan.nextInt());

    }

    // This method that prints out the User 2's information and prints it out 

    public void obtainUser2Info() {

        // The Scanner class is used to obtain the user 2's information

        System.out.println("\n" + "User 2, please enter your first name: ");
        setFirstName(scan.nextLine());

        System.out.println("\n" + "Please enter your last name: ");
        setLastName(scan.nextLine());

        System.out.println("\n" + "Please enter your email: ");
        setEmail(scan.nextLine());

        System.out.println("\n" + "Please enter your favorite color: ");
        setFavoriteColor(scan.nextLine());

        System.out.println("\n" + "Please enter your favorite animal: ");
        setFavoriteAnimal(scan.nextLine());

        System.out.println("\n" + "Please enter your favorite number: ");
        setFavoriteNumber(scan.nextInt());

    }
    }
     